name: 'Terraform Checks'

on: [push, pull_request]
env:
  tf_version: '0.13.5'

jobs:
  build:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ${{ env.tf_version }}

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -recursive -no-color -check -diff

      # Static analyse tool for terraform
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail --exclude-downloaded-modules
          github_token: ${{ github.token }}
