name: 'Terraform Checks'

on: [pull_request]

jobs:
  build:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform Format
        run: terraform fmt -recursive -no-color -check -diff

      - name: Tfsec PR Commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail --exclude-downloaded-modules
          github_token: ${{ github.token }}

      - name: Tfsec Run Check and Generate SARIF File
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
